bananaChoc=int(input())
mangoChoc=int(input())
bananaChocEaten=int(input())
mangoChocEaten=int(input())
mainOutputText = 2*(bananaChoc - bananaChocEaten + mangoChoc - mangoChocEaten)
print(mainOutputText)