t1 = int(input())
t2 = int(input())
t3 = int(input())
t4 = int(input())
numbers = [t1, t2, t3, t4]
biggestnumber = max(numbers)
numbers.remove(biggestnumber)
secondbiggestnumber = max(numbers)
numbers.remove(secondbiggestnumber)
print(biggestnumber*10 + secondbiggestnumber)
thirdnumber = max(numbers)
numbers.remove(thirdnumber)
fourthnumber = max(numbers)
print(biggestnumber*1000+secondbiggestnumber*100+thirdnumber*10+fourthnumber)
